all:
	gcc -Wall -g -fno-pie -fno-stack-protector -m32 ./units.c -o units
	gcc -Wall -g -fno-pie -fno-stack-protector -m32 ./task1.c -o task1
	gcc -Wall -g -fno-pie -fno-stack-protector -m32 ./task4.c -o task4

.PHONY: clean
	
clean:
	rm -f ./units ./task1 ./task4
